-- 코드를 입력하세요
SELECT ANIMAL_INS.name AS 'NAME', ANIMAL_INS.datetime AS 'DATETIME' 
FROM ANIMAL_INS
LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.datetime IS NULL
ORDER BY ANIMAL_INS.datetime
LIMIT 3;