-- 코드를 입력하세요
SELECT I.REST_ID, I.REST_NAME, I.FOOD_TYPE, I.FAVORITES, I.ADDRESS, ROUND(AVG(R.REVIEW_SCORE), 2) AS 'SCORE'
FROM REST_INFO I
JOIN REST_REVIEW R ON I.REST_ID = R.REST_ID
WHERE LEFT(I.ADDRESS, 2) IN ('서울')
GROUP BY I.REST_ID
order by SCORE DESC, I.FAVORITES DESC;